# Site wide configuration

title:  Martín Opertti
locale: es_UY
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Martín Opertti
  avatar: fototw.jpg
  bio: "¡Bienvenido! Soy licenciado en sociología y trabajo como asistente en proyectos de investigación sobre opinión pública y comportamiento político en el Departamento de Ciencias Sociales de la Universidad Católica del Uruguay, donde también soy docente de grado. Mi trabajo aparece en publicaciones como la Revista Latinoamericana de Opinión Pública y soy co-autor del libro Twittarquía, la política de las redes en Uruguay.
  Mis principales intereses de investigación se enmarcan en el estudio del comportamiento político de masas y los métodos de investigación. Particularmente estudio los orígenes y consecuencias de las identificaciones partidarias, los determinantes (particularmente económicos) del voto, la polarización política y el uso político de redes sociales. A su vez, me interesa el análisis de redes sociales, la metodología de encuestas y la visualización de datos."
  email: operttim@gmail.com
  # Do not include the @ symbol in your Twitter username
  twitter: martinopertti
  github: martinopertti

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#228B22'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
